#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef ROX_SWIFT_H
#define ROX_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ROX",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;
@class ROXOptions;
@class ROXBaseContainer;
@class NSNumber;
@class ROXFlag;

/// ROXConfiguration represents a single SDK instance configuration.
/// Each configuration is identified by a unique SDK key and name, and manages its own
/// set of feature flags, custom properties, and options. This enables multiple independent
/// ROX configurations to coexist in the same application.
/// Configurations can be used to:
/// <ul>
///   <li>
///     Manage different environments (staging, production)
///   </li>
///   <li>
///     Support multiple tenants or organizations
///   </li>
///   <li>
///     Test different feature sets independently
///   </li>
/// </ul>
/// Example usage:
/// \code
/// // Create and set up a production configuration
/// let prodConfig = try ROXConfiguration(key: "prod_key", name: "production")
/// prodConfig.setup()
/// prodConfig.setCustomStringProperty("prod", forKey: "env")
///
/// // Create and set up a staging configuration
/// let stageConfig = try ROXConfiguration(key: "stage_key", name: "staging")
/// stageConfig.setup()
/// stageConfig.setCustomStringProperty("stage", forKey: "env")
///
/// // Register feature containers
/// let container = FeaturesContainer()
/// prodConfig.register(container)
/// stageConfig.register(container)
///
/// \endcodeFor easier management of multiple configurations, use <code>ROXConfigurationManager</code>
/// and <code>ROXOperations</code>. See <code>ROXConfigurationManager</code> for more details.
SWIFT_CLASS("_TtC3ROX16ROXConfiguration")
@interface ROXConfiguration : NSObject
/// Initialize with SDK key and optional name
/// \param key The SDK key for this configuration
///
/// \param name Optional name for this configuration. If not provided or empty, a name will be generated from the SDK key
///
///
/// throws:
/// ROXError if the key is empty or invalid
- (nullable instancetype)initWithKey:(NSString * _Nonnull)key name:(NSString * _Nonnull)name error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
/// Set up this configuration with ROXCore
- (void)setup;
/// Set up this configuration with options
- (void)setupWithOptions:(ROXOptions * _Nonnull)options;
/// Check if this configuration is ready
@property (nonatomic, readonly) BOOL isReady;
/// Fetch latest configuration from server
- (void)fetch;
/// Register a container with this configuration
- (void)register:(ROXBaseContainer * _Nonnull)container;
/// Shutdown this configuration
- (void)shutdown;
/// Set a custom string property
- (void)setCustomStringProperty:(NSString * _Nonnull)value forKey:(NSString * _Nonnull)key;
/// Set a custom boolean property
- (void)setCustomBooleanProperty:(BOOL)value forKey:(NSString * _Nonnull)key;
/// Set a custom number property
- (void)setCustomNumberProperty:(NSNumber * _Nonnull)value forKey:(NSString * _Nonnull)key;
/// Register a feature flag
- (void)registerFlag:(ROXFlag * _Nonnull)flag withKey:(NSString * _Nonnull)key;
/// Get a feature flag by key
- (ROXFlag * _Nullable)flagForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
/// Unfreeze all flags for this configuration
- (void)unfreeze;
/// Add a flag to this configuration
/// \param flag The flag to add
///
/// \param key The key for the flag
///
- (void)addFlag:(ROXFlag * _Nonnull)flag forKey:(NSString * _Nonnull)key;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSError;

/// ROXConfigurationManager provides centralized management of multiple SDK configurations.
/// It maintains a thread-safe registry of configurations and handles the default configuration
/// for backward compatibility with existing code.
/// Key features:
/// <ul>
///   <li>
///     Thread-safe configuration management
///   </li>
///   <li>
///     Support for multiple independent configurations
///   </li>
///   <li>
///     Backward compatibility via default configuration
///   </li>
///   <li>
///     Automatic namespacing of properties and flags
///   </li>
/// </ul>
/// Example usage:
/// \code
/// // Setup multiple configurations
/// try ROXConfigurationManager.setup(withKey: "prod_key", name: "production")
/// try ROXConfigurationManager.setup(withKey: "stage_key", name: "staging")
///
/// // Access configurations via ROX.using
/// if let prodOps = ROX.using("production") {
///     prodOps.setCustomStringProperty(key: "env", value: "prod")
///     prodOps.register(FeaturesContainer())
/// }
///
/// if let stageOps = ROX.using("staging") {
///     stageOps.setCustomStringProperty(key: "env", value: "stage")
///     stageOps.register(FeaturesContainer())
/// }
///
/// // Check if configuration exists
/// if ROXConfigurationManager.exists("production") {
///     // Use the configuration
/// }
///
/// // Get default configuration (for backward compatibility)
/// if let defaultConfig = ROXConfigurationManager.getDefault() {
///     // Use default configuration
/// }
///
/// \endcodeFor configuration-specific operations, use <code>ROXOperations</code> obtained via <code>ROX.using(_:)</code>.
/// See <code>ROXOperations</code> and <code>ROXConfiguration</code> for more details.
SWIFT_CLASS("_TtC3ROX23ROXConfigurationManager")
@interface ROXConfigurationManager : NSObject
/// Debug mode flag for logging context switches and configuration operations
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL debugMode;)
+ (BOOL)debugMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setDebugMode:(BOOL)value;
/// Add a new configuration with the given key and optional name
/// \param key The SDK key for the configuration
///
/// \param name Optional name for the configuration. If not provided, one will be generated from the key
///
///
/// throws:
/// ROXError if the configuration is invalid or a duplicate
///
/// returns:
/// The created configuration
+ (ROXConfiguration * _Nullable)addWithKey:(NSString * _Nonnull)key name:(NSString * _Nonnull)name error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Objective-C friendly version of add that uses error pointer instead of throws
+ (ROXConfiguration * _Nullable)addConfigurationWithKey:(NSString * _Nonnull)key name:(NSString * _Nonnull)name error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
+ (ROXConfiguration * _Nullable)get:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
+ (ROXConfiguration * _Nullable)getDefault SWIFT_WARN_UNUSED_RESULT;
/// Get the configuration name that was generated or provided for a given SDK key
/// \param key The SDK key
///
///
/// returns:
/// The configuration name, or nil if not found
+ (NSString * _Nullable)getConfigurationNameForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
+ (void)setDefault:(ROXConfiguration * _Nonnull)configuration;
+ (BOOL)exists:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
/// Set up a new configuration with the given key and name
/// \param key The SDK key for the configuration
///
/// \param name Name for the configuration
///
///
/// throws:
/// ROXError if configuration is invalid or duplicate
+ (BOOL)setupWithKey:(NSString * _Nonnull)key name:(NSString * _Nonnull)name error:(NSError * _Nullable * _Nullable)error;
/// Objective-C friendly version of setup that uses error pointer instead of throws
/// \param key The SDK key for the configuration
///
/// \param name Name for the configuration
///
/// \param error Error pointer for Objective-C error handling
///
///
/// returns:
/// true if setup was successful, false if an error occurred
+ (BOOL)setupConfigurationWithKey:(NSString * _Nonnull)key name:(NSString * _Nonnull)name error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
+ (void)removeAll;
/// Get all configuration names
///
/// returns:
/// Array of configuration names
+ (NSArray<NSString *> * _Nonnull)getAllConfigurationNames SWIFT_WARN_UNUSED_RESULT;
/// Get configuration by SDK key
/// \param key The SDK key
///
///
/// returns:
/// The configuration with the given SDK key, or nil if not found
+ (ROXConfiguration * _Nullable)getConfigurationByKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
/// Shutdown all configurations
+ (void)shutdown;
/// Shutdown a specific configuration by name
/// \param name The name of the configuration to shutdown
///
+ (void)shutdown:(NSString * _Nonnull)name;
/// Get the active configuration
///
/// returns:
/// The active configuration, or nil if none is active
+ (ROXConfiguration * _Nullable)getActiveConfiguration SWIFT_WARN_UNUSED_RESULT;
/// Set the active configuration
/// This method updates the currently active configuration and ensures that
/// the SDK key context is properly updated. It’s a critical part of the multi-SDK
/// implementation as it maintains the correct context for subsequent operations.
/// When a configuration becomes active:
/// <ol>
///   <li>
///     It’s registered as the active configuration in the manager
///   </li>
///   <li>
///     The SDK key context is updated in ROXSDKKeyTracker
///   </li>
///   <li>
///     ROXCore is set up with the correct SDK key
///   </li>
///   <li>
///     Device properties and repositories are switched to the correct context
///   </li>
/// </ol>
/// \param configuration The configuration to set as active
///
+ (void)setActiveConfiguration:(ROXConfiguration * _Nonnull)configuration;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// ROXOperations provides configuration-specific operations that mirror the static ROX methods.
/// Each instance is associated with a specific ROXConfiguration and provides methods to
/// manage feature flags, custom properties, and other SDK operations for that configuration.
/// This enables isolated management of features and properties across different configurations.
/// Key features:
/// <ul>
///   <li>
///     Configuration-specific property management
///   </li>
///   <li>
///     Isolated feature flag registration
///   </li>
///   <li>
///     Computed property support
///   </li>
///   <li>
///     Global context management
///   </li>
///   <li>
///     Flag overrides and dynamic API access
///   </li>
/// </ul>
/// Example usage:
/// \code
/// // Get operations for a specific configuration
/// if let ops = ROX.using("production") {
///     // Set static properties
///     ops.setCustomStringProperty(key: "env", value: "prod")
///     ops.setCustomBooleanProperty(key: "enabled", value: true)
///     
///     // Set computed properties
///     ops.setCustomStringProperty(key: "region") { _, ctx in
///         return getCurrentRegion()
///     }
///     
///     // Register feature containers
///     ops.register(FeaturesContainer())
///     
///     // Manage flags
///     ops.fetch()
///     ops.unfreeze()
///     
///     // Access flag overrides
///     let overrides = ops.overrides()
///     overrides.setOverride("flag_key", value: true)
/// }
///
/// \endcodeROXOperations instances should be obtained via <code>ROX.using(_:)</code> rather than created directly.
/// See <code>ROXConfigurationManager</code> for configuration management and <code>ROXConfiguration</code> for
/// configuration setup.
SWIFT_CLASS("_TtC3ROX13ROXOperations")
@interface ROXOperations : NSObject
/// Set up the associated configuration
- (void)setup;
/// Set up the associated configuration with options
- (void)setupWithOptions:(ROXOptions * _Nonnull)options;
/// Shutdown the associated configuration
- (void)shutdown;
/// Check if the associated configuration is ready
@property (nonatomic, readonly) BOOL isReady;
/// Fetch latest configuration from server
- (void)fetch;
/// Register a container with this configuration
/// This method ensures that flags are registered in the correct SDK context and properly namespaced
/// based on the configuration’s name. It uses the configuration-specific registration path
/// that maintains isolation between different SDK instances.
/// \param container The container with feature flags to register
///
- (void)register:(ROXBaseContainer * _Nonnull)container;
/// Unfreeze all flags for this configuration
- (void)unfreeze;
/// Set a custom string property for this configuration
/// \param key The property key
///
/// \param value The string value
///
- (void)setCustomStringPropertyWithKey:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
/// Set a custom boolean property for this configuration
/// \param key The property key
///
/// \param value The boolean value
///
- (void)setCustomBooleanPropertyWithKey:(NSString * _Nonnull)key value:(BOOL)value;
/// Set a custom number property for this configuration
/// \param key The property key
///
/// \param value The number value
///
- (void)setCustomNumberPropertyWithKey:(NSString * _Nonnull)key value:(NSNumber * _Nonnull)value;
/// Set environment properties for this configuration (Objective-C compatible version)
/// \param environment The environment name (e.g., “production”, “staging”)
///
- (void)setEnvironment:(NSString * _Nonnull)environment;
/// Set environment properties for this configuration (Objective-C compatible version)
/// \param environment The environment name (e.g., “production”, “staging”)
///
/// \param version App version
///
- (void)setEnvironment:(NSString * _Nonnull)environment version:(NSString * _Nonnull)version;
/// Set environment properties for this configuration (Objective-C compatible version)
/// \param environment The environment name (e.g., “production”, “staging”)
///
/// \param version App version
///
/// \param platform Platform identifier
///
- (void)setEnvironment:(NSString * _Nonnull)environment version:(NSString * _Nonnull)version platform:(NSString * _Nonnull)platform;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC3ROX16ROXSDKKeyTracker")
@interface ROXSDKKeyTracker : NSObject
/// Get the current SDK key - accessible from Objective-C
+ (NSString * _Nullable)getCurrentSDKKey SWIFT_WARN_UNUSED_RESULT;
/// Execute a block with a specific SDK key context (Objective-C compatible version)
/// \param sdkKey The SDK key to use during the block execution
///
/// \param block The block to execute
///
+ (void)withSDKKeyObjC:(NSString * _Nonnull)sdkKey block:(void (^ _Nonnull)(void))block;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
